name: ðŸ’° Fetch Paypal transactions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  schedule:
    name: ðŸ’° Fetch Paypal transactions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl ssh console -C "python manage.py fetch_paypal_transactions"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
