name: Process Cora emails

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  schedule:
    name: ðŸ’° Process Cora emails
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl ssh console -C "python manage.py process_cora_email"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
